In [1]:
#Install Packages
!pip install faiss-cpu
!pip install sentence-transformers

Collecting faiss-cpu
  Downloading faiss_cpu-1.14.3-cp314-cp314-win_amd64.whl.metadata (7.8 kB)
Requirement already satisfied: numpy>=1.25 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from faiss-cpu) (2.4.6)
Requirement already satisfied: packaging in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from faiss-cpu) (26.0)
Downloading faiss_cpu-1.14.3-cp314-cp314-win_amd64.whl (16.4 MB)
   ---------------------------------------- 0.0/16.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.4 MB ? eta -:--:--
    --------------------------------------- 0.3/16.4 MB ? eta -:--:--
   - -------------------------------------- 0.8/16.4 MB 1.4 MB/s eta 0:00:12
   - -------------------------------------- 0.8/16.4 MB 1.4 MB/s eta 0:00:12
   -- ------------------------------------- 1.0/16.4 MB 1.3 MB/s eta 0:00:12
   --- ------------------------------------ 1.3/16.4 MB 1.3 MB/s eta 0:00:12
   ---- ----------------------------------- 1.8/16.4 MB 1.3 MB/s eta 0:00:12
   ----- ---------------------------------- 2.1/16.4 MB 1.3 MB/s eta 0:00:12
   ----- ---------------------------------- 2.4/16.4 MB 1.3 MB/s eta 0:00:11
   ------ --------------------------------- 2.6/16.4 MB 1.4 MB/s eta 0:00:10
   ------- -------------------------------- 2.9/16.4 MB 1.4 MB/s eta 0:00:10
   -------- ------------------------------- 3.4/16.4 MB 1.4 MB/s eta 0:00:10
   -------- ------------------------------- 3.7/16.4 MB 1.4 MB/s eta 0:00:10
   --------- ------------------------------ 3.9/16.4 MB 1.4 MB/s eta 0:00:09
   ---------- ----------------------------- 4.2/16.4 MB 1.4 MB/s eta 0:00:09
   ---------- ----------------------------- 4.5/16.4 MB 1.4 MB/s eta 0:00:09
   ----------- ---------------------------- 4.7/16.4 MB 1.4 MB/s eta 0:00:09
   ------------ --------------------------- 5.2/16.4 MB 1.4 MB/s eta 0:00:08
   ------------- -------------------------- 5.5/16.4 MB 1.5 MB/s eta 0:00:08
   -------------- ------------------------- 6.0/16.4 MB 1.5 MB/s eta 0:00:07
   --------------- ------------------------ 6.6/16.4 MB 1.6 MB/s eta 0:00:07
   ----------------- ---------------------- 7.1/16.4 MB 1.6 MB/s eta 0:00:06
   ----------------- ---------------------- 7.3/16.4 MB 1.6 MB/s eta 0:00:06
   ------------------ --------------------- 7.6/16.4 MB 1.6 MB/s eta 0:00:06
   ------------------- -------------------- 8.1/16.4 MB 1.6 MB/s eta 0:00:06
   -------------------- ------------------- 8.4/16.4 MB 1.6 MB/s eta 0:00:05
   --------------------- ------------------ 8.7/16.4 MB 1.6 MB/s eta 0:00:05
   --------------------- ------------------ 8.9/16.4 MB 1.6 MB/s eta 0:00:05
   ---------------------- ----------------- 9.2/16.4 MB 1.6 MB/s eta 0:00:05
   ---------------------- ----------------- 9.4/16.4 MB 1.6 MB/s eta 0:00:05
   ------------------------ --------------- 10.0/16.4 MB 1.6 MB/s eta 0:00:05
   ------------------------ --------------- 10.2/16.4 MB 1.6 MB/s eta 0:00:04
   ------------------------- -------------- 10.5/16.4 MB 1.6 MB/s eta 0:00:04
   -------------------------- ------------- 10.7/16.4 MB 1.6 MB/s eta 0:00:04
   -------------------------- ------------- 11.0/16.4 MB 1.6 MB/s eta 0:00:04
   ---------------------------- ----------- 11.8/16.4 MB 1.6 MB/s eta 0:00:03
   ----------------------------- ---------- 12.1/16.4 MB 1.6 MB/s eta 0:00:03
   ------------------------------ --------- 12.6/16.4 MB 1.6 MB/s eta 0:00:03
   ------------------------------- -------- 12.8/16.4 MB 1.6 MB/s eta 0:00:03
   ------------------------------- -------- 12.8/16.4 MB 1.6 MB/s eta 0:00:03
   --------------------------------- ------ 13.6/16.4 MB 1.6 MB/s eta 0:00:02
   ---------------------------------- ----- 14.2/16.4 MB 1.6 MB/s eta 0:00:02
   ----------------------------------- ---- 14.4/16.4 MB 1.6 MB/s eta 0:00:02
   ------------------------------------ --- 15.2/16.4 MB 1.7 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.4 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.4 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 16.0/16.4 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  16.3/16.4 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 16.4/16.4 MB 1.6 MB/s  0:00:10
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.14.3

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting sentence-transformers
  Using cached sentence_transformers-5.6.0-py3-none-any.whl.metadata (18 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-5.13.1-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub>=0.23.0 (from sentence-transformers)
  Using cached huggingface_hub-1.23.0-py3-none-any.whl.metadata (14 kB)
Collecting torch>=1.11.0 (from sentence-transformers)
  Using cached torch-2.13.0-cp314-cp314-win_amd64.whl.metadata (39 kB)
Requirement already satisfied: numpy>=1.20.0 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from sentence-transformers) (2.4.6)
Collecting scikit-learn>=0.22.0 (from sentence-transformers)
  Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: scipy>=1.0.0 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from sentence-transformers) (4.68.3)
Requirement already satisfied: packaging>=20.0 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.6.28)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typer in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.26.7)
Collecting safetensors>=0.8.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub>=0.23.0->sentence-transformers)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting filelock>=3.10.0 (from huggingface-hub>=0.23.0->sentence-transformers)
  Using cached filelock-3.29.7-py3-none-any.whl.metadata (2.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.23.0->sentence-transformers)
  Using cached fsspec-2026.6.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.5.1 (from huggingface-hub>=0.23.0->sentence-transformers)
  Using cached hf_xet-1.5.1-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: colorama in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub>=0.23.0->sentence-transformers) (0.4.6)
Requirement already satisfied: anyio in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.0)
Requirement already satisfied: certifi in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Collecting narwhals>=2.0.1 (from scikit-learn>=0.22.0->sentence-transformers)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn>=0.22.0->sentence-transformers)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from torch>=1.11.0->sentence-transformers) (82.0.1)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\addwi\appdata\roaming\python\python314\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\addwi\appdata\local\programs\python\python314\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Using cached sentence_transformers-5.6.0-py3-none-any.whl (596 kB)
Downloading transformers-5.13.1-py3-none-any.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 649.3 kB/s eta 0:00:17
   -- ------------------------------------- 0.8/11.5 MB 763.1 kB/s eta 0:00:15
   -- ------------------------------------- 0.8/11.5 MB 763.1 kB/s eta 0:00:15
   --- ------------------------------------ 1.0/11.5 MB 692.1 kB/s eta 0:00:16
   ---- ----------------------------------- 1.3/11.5 MB 765.5 kB/s eta 0:00:14
   ---- ----------------------------------- 1.3/11.5 MB 765.5 kB/s eta 0:00:14
   ----- ---------------------------------- 1.6/11.5 MB 787.8 kB/s eta 0:00:13
   ------ --------------------------------- 1.8/11.5 MB 849.5 kB/s eta 0:00:12
   ------- -------------------------------- 2.1/11.5 MB 893.1 kB/s eta 0:00:11
   -------- ------------------------------- 2.4/11.5 MB 937.1 kB/s eta 0:00:10
   ---------- ----------------------------- 2.9/11.5 MB 1.0 MB/s eta 0:00:09
   ---------- ----------------------------- 3.1/11.5 MB 1.0 MB/s eta 0:00:09
   ------------ --------------------------- 3.7/11.5 MB 1.1 MB/s eta 0:00:07
   ------------- -------------------------- 3.9/11.5 MB 1.1 MB/s eta 0:00:07
   --------------- ------------------------ 4.5/11.5 MB 1.2 MB/s eta 0:00:06
   ---------------- ----------------------- 4.7/11.5 MB 1.2 MB/s eta 0:00:06
   ------------------ --------------------- 5.2/11.5 MB 1.3 MB/s eta 0:00:05
   -------------------- ------------------- 5.8/11.5 MB 1.4 MB/s eta 0:00:05
   --------------------- ------------------ 6.3/11.5 MB 1.4 MB/s eta 0:00:04
   ----------------------- ---------------- 6.8/11.5 MB 1.5 MB/s eta 0:00:04
   -------------------------- ------------- 7.6/11.5 MB 1.5 MB/s eta 0:00:03
   --------------------------- ------------ 7.9/11.5 MB 1.6 MB/s eta 0:00:03
   ---------------------------- ----------- 8.1/11.5 MB 1.6 MB/s eta 0:00:03
   ------------------------------ --------- 8.9/11.5 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 9.4/11.5 MB 1.6 MB/s eta 0:00:02
   ---------------------------------- ----- 10.0/11.5 MB 1.7 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.5 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.5 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.5 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 1.7 MB/s  0:00:07
Using cached huggingface_hub-1.23.0-py3-none-any.whl (770 kB)
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Using cached hf_xet-1.5.1-cp37-abi3-win_amd64.whl (4.0 MB)
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Using cached filelock-3.29.7-py3-none-any.whl (46 kB)
Using cached fsspec-2026.6.0-py3-none-any.whl (203 kB)
Using cached safetensors-0.8.0-cp310-abi3-win_amd64.whl (355 kB)
Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached torch-2.13.0-cp314-cp314-win_amd64.whl (122.1 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, threadpoolctl, sympy, safetensors, narwhals, hf-xet, fsspec, filelock, click, torch, scikit-learn, huggingface-hub, tokenizers, transformers, sentence-transformers

   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   ----------------------------------------  0/15 [mpmath]
   -- -------------------------------------  1/15 [threadpoolctl]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]
   ----- ----------------------------------  2/15 [sympy]

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# import necessary libraries
import pandas as pd
pd.set_option('display.max_colwidth', 100)

In [3]:
df = pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [4]:
df

,text,category
0,Meditation and yoga can improve mental health,Health
1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,These are the latest fashion trends for this week,Fashion
3,Vibrant color jeans for male are becoming a trend,Fashion
4,The concert starts at 7 PM tonight,Event
5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,Exciting vacation destinations for your next trip,Travel
7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel

Step 1 : Create source embeddings for the text column

In [5]:
from sentence_transformers import SentenceTransformer

C:\Users\addwi\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
encoder = SentenceTransformer("all-mpnet-base-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2006.98it/s]

In [22]:
vectors = encoder.encode(df["text"].tolist())
vectors.shape

(8, 768)

In [24]:
dim = vectors.shape[1]
dim

768

Step 2 : Build a FAISS Index for vectors

In [25]:
import faiss

index = faiss.IndexFlatL2(dim)

Step 3 : Normalize the source vectors (as we are using L2 distance to measure similarity) and add to the index

In [26]:
index.add(vectors)

In [27]:
index

Step 4 : Encode search text using same encorder and normalize the output vector

In [28]:
search_query = "I want to buy a polo t-shirt"
# search_query = "looking for places to visit during the holidays"
# search_query = "An apple a day keeps the doctor away"
vec = encoder.encode(search_query)
vec.shape

(768,)

In [29]:
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

Step 5: Search for similar vector in the FAISS index created

In [33]:
distances , I = index.search(svec, k = 2 )

In [34]:
distances

array([[1.3844836, 1.4039092]], dtype=float32)

In [35]:
 I

array([[3, 2]])

In [36]:
I.tolist()

[[3, 2]]

In [37]:
row_indices = I.tolist()[0]
row_indices

[3, 2]

In [38]:
df.loc[row_indices]

                                                text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion

In [39]:
search_query

'I want to buy a polo t-shirt'